//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID { get; set; }
        public string USUARIO1 { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> ESTADO { get; set; }
    
        public virtual ESTADO ESTADO1 { get; set; }
    }
}
